apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui-2
spec:	
  selector:	
    app: guestbook-ui-2

apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-2
spec:
  selector:
    matchLabels:
      app: guestbook-ui-2
  template:
    metadata:
      labels:
        app: guestbook-ui-2
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-ui-2